const ABILITIES_DATA = [
  {
    name: "Careful Observation",
    type: "Investigator",
    supernatural: false,
    tier: 1,
    description:
      "If you succeed at a difficulty 4 perception task, you take note of an inanimate object within an immediate distance that is related to your current investigation. You see some detail that another person would have likely passed over. If there is no such detail in the area, you learn that too (and know that you can move on, as there’s nothing of note there). If there are two or more such details, you still just make one roll; you learn one detail if you succeed at a difficulty 4 task, a second detail if you succeed at a difficulty 5 task, the third detail if you succeed at a difficulty 6 task, and so forth.",
    stat: "Intellect",
    pointsRequired: 1,
    stress: 0,
  },
  {
    name: "Decipher",
    type: "Investigator",
    supernatural: false,
    tier: 1,
    description:
      "If you spend one minute examining a piece of writing or code in a language you don’t understand, you can make an Intellect roll to get the gist of the message. The difficulty is usually 3 but may be higher based on the complexity of the language or code. Action to initiate; one minute to complete.",
    stat: "Intellect",
    pointsRequired: 1,
    stress: 0,
  },
  {
    name: "Fleet of Foot",
    type: "Investigator",
    supernatural: false,
    tier: 1,
    description:
      "Instead of being able to move an immediate distance as part of another action, you can move a short distance as part of another action. Instead of moving a short distance as your entire action for a turn, you can move a long distance. If you apply a level of Effort to this ability, you can move a long distance and make an attack as your entire action for a turn, but the attack is hindered.",
    stat: "Speed",
    pointsRequired: 1,
    stress: 0,
  },
  {
    name: "Follow the Trail",
    type: "Investigator",
    supernatural: false,
    tier: 1,
    description:
      "When you apply Effort to a perception or tracking task because you are attempting to find a specific person or place, you can apply a free level of Effort.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Knowledge Skills",
    type: "Investigator",
    supernatural: false,
    tier: 1,
    description:
      "You are trained in two skills in which you are not already trained. Choose two areas of knowledge such as history, geography, forensics, and so on. You can select this ability multiple times. Each time you select it, you must choose two different skills.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Missing Detail",
    type: "Investigator",
    supernatural: false,
    tier: 1,
    description:
      "You listen to the words of an NPC, read a transcript of something that was said, or read an account written by someone—such as a statement—and you immediately note something that wasn’t said. This can be something implied by what was said or written, or something obviously left out. The GM provides this brief fact to you. The words written or spoken must be substantial, like someone giving an eyewitness account, telling a story, or—as previously mentioned—giving a statement.",
    stat: "Intellect",
    pointsRequired: 2,
    stress: 0,
  },
  {
    name: "Operate in the Dark",
    type: "Investigator",
    supernatural: false,
    tier: 1,
    description:
      "For the next hour, you use your other senses to compensate for a lack of vision. If you’re blinded or just in the dark, you operate without any hindrance. Action to initiate.",
    stat: "Intellect",
    pointsRequired: 1,
    stress: 0,
  },
  {
    name: "Ready for Danger",
    type: "Investigator",
    supernatural: false,
    tier: 1,
    description: "You are trained in initiative.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Surging Confidence",
    type: "Investigator",
    supernatural: false,
    tier: 1,
    description:
      "You can use your one-action recovery roll as part of another action.",
    stat: "Might",
    pointsRequired: 1,
    stress: 0,
  },
  {
    name: "Escape",
    type: "Investigator",
    supernatural: false,
    tier: 2,
    description:
      "You slip your restraints, squeeze through the bars, break the grip of the creature holding you, pull free from sucking quicksand, or otherwise get loose from whatever is holding you in place.",
    stat: "Speed",
    pointsRequired: 2,
    stress: 0,
  },
  {
    name: "Eye for Detail",
    type: "Investigator",
    supernatural: false,
    tier: 2,
    description:
      "When you spend at least five minutes thoroughly exploring an area no larger than a short distance in diameter, you can ask the GM one question about the area and get an answer. You cannot use this more than one time per area per 24 hours. Action to initiate; five minutes to complete.",
    stat: "Intellect",
    pointsRequired: 2,
    stress: 0,
  },
  {
    name: "Hand to Eye",
    type: "Investigator",
    supernatural: false,
    tier: 2,
    description:
      "This ability provides an asset to any tasks involving manual dexterity, such as pickpocketing, lockpicking, games involving agility, and so on, for one minute. Action to initiate.",
    stat: "Speed",
    pointsRequired: 2,
    stress: 0,
  },
  {
    name: "Just a Hunch",
    type: "Investigator",
    supernatural: false,
    tier: 2,
    description:
      "A flash of insight provides you with a small clue or suggests a course of action with regard to an urgent question, problem, or obstacle you’re facing when you have no idea how to proceed. Once you use this ability, you can’t use it again until after your next ten-hour recovery roll, and then only if you’ve followed up on the clue or course of action suggested by your last hunch. Action.",
    stat: "Intellect",
    pointsRequired: 2,
    stress: 0,
  },
  {
    name: "Research",
    type: "Investigator",
    supernatural: false,
    tier: 2,
    description:
      "If you spend at least two hours with an appropriate source of information (such as the internet, a library, the archives, or a single informative book), you learn one relevant fact about a topic you choose. Essentially, you ask the GM a question and they give you an answer appropriate for the topic based on the source. The internet or a small-town library might not have accurate esoteric occult information, while a book on ancient architecture might have everything you need on that topic.",
    stat: "Intellect",
    pointsRequired: 2,
    stress: 0,
  },
  {
    name: "Skill with Defence",
    type: "Investigator",
    supernatural: false,
    tier: 2,
    description:
      "Choose one type of defense task in which you are not already trained: Might, Speed, or Intellect. You are trained in defense tasks of that type.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Skim",
    type: "Investigator",
    supernatural: false,
    tier: 2,
    description:
      "Taking just a minute, you can skim through a book, a computer database, a diary, an accounting ledger, or a similar information source and get the gist of the contents. If you succeed at a difficulty 4 Intellect-based task, you also learn a prominent or surprising bit of information you didn’t already know. Action to initiate; one minute to complete.",
    stat: "Intellect",
    pointsRequired: 2,
    stress: 0,
  },
  {
    name: "Surveillance",
    type: "Investigator",
    supernatural: false,
    tier: 2,
    description:
      "All tasks involving monitoring, watching, or tailing a person or place are eased.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Travel Skills",
    type: "Investigator",
    supernatural: false,
    tier: 2,
    description:
      "You are trained in two skills in which you are not already trained. Choose two of the following: driving, endurance, geography, piloting, or riding. You can select this ability multiple times. Each time you select it, you must choose two different skills.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Interaction Skills",
    type: "Investigator",
    supernatural: false,
    tier: 3,
    description:
      "You are trained in two skills in which you are not already trained. Choose two of the following: deception, discerning motive, intimidation, or persuasion. You can select this ability multiple times. Each time you select it, you must choose two different skills.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Quick Recovery",
    type: "Investigator",
    supernatural: false,
    tier: 3,
    description: "Your ten-minute recovery roll is only a single action.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Scarred and Hardened",
    type: "Investigator",
    supernatural: false,
    tier: 3,
    description:
      "You reduce the Stress you suffer from physical injury by 1. You still suffer Stress from mental shock or despair normally.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Seen Some… Stuff",
    type: "Investigator",
    supernatural: false,
    tier: 3,
    description:
      "You reduce the Stress you suffer from mental shock or despair by 1. You still suffer Stress from physical injury normally.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Skill with Attacks",
    type: "Investigator",
    supernatural: false,
    tier: 3,
    description:
      "Choose one type of attack in which you are not already trained: light bashing, light bladed, light ranged, medium bashing, medium bladed, medium ranged, heavy bashing, heavy bladed, or heavy ranged. You are trained in attacks using that type of weapon. You can select this ability multiple times. Each time you select it, you must choose a different type of attack.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Think Your Way Out",
    type: "Investigator",
    supernatural: false,
    tier: 3,
    description:
      "You can use points from your Intellect Pool rather than your Might Pool or Speed Pool on any noncombat action.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Trapfinder",
    type: "Investigator",
    supernatural: false,
    tier: 3,
    description:
      "You find any traps (like a floor that would give way beneath you) or mechanical triggers to a trap or defense system that might pose a threat. You can do this without setting them off and in lieu of making a roll to find them. This ability automatically finds traps of level 4 or below. You can use Effort to increase the level of traps that can be found by 2, so using two levels of Effort can find all traps of level 8 and below. Action.",
    stat: "Intellect",
    pointsRequired: 3,
    stress: 0,
  },
  {
    name: "Unnatural Dream",
    type: "Investigator",
    supernatural: true,
    tier: 3,
    description:
      "When you fall asleep, you have a dream that provides insight into a situation you currently face (although you do not consciously choose the topic). The GM provides you with the information you learn, probably details you couldn’t learn conventionally. Action.",
    stat: "Intellect",
    pointsRequired: 3,
    stress: 3,
  },
  {
    name: "Credible Hypothesis",
    type: "Investigator",
    supernatural: false,
    tier: 4,
    description:
      "You examine an immediate area (basically an average room) and learn precise, useful details about the past (if any exist). You can ask the GM up to four questions about the immediate area; each requires its own roll (the GM determines the difficulty, but the default is level 4). Action.",
    stat: "Intellect",
    pointsRequired: 4,
    stress: 0,
  },
  {
    name: "Heightened Skills",
    type: "Investigator",
    supernatural: false,
    tier: 4,
    description:
      "You are trained in two tasks of your choosing (other than attacks or defense). If you choose a task you’re already trained in, you instead become specialized in that task. You can’t choose a task you’re already specialized in.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Look for the Tell",
    type: "Investigator",
    supernatural: false,
    tier: 4,
    description:
      "After spending at least a minute with a person in conversation, for the next minute you know when they are lying. Action to initiate.",
    stat: "Intellect",
    pointsRequired: 4,
    stress: 0,
  },
  {
    name: "Perfect Tracker",
    type: "Investigator",
    supernatural: false,
    tier: 4,
    description:
      "If you find a set of tracks, you can follow them without error unless the conditions absolutely prohibit it (heavy rain, complete darkness, etc.)",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Subtle Steps",
    type: "Investigator",
    supernatural: false,
    tier: 4,
    description:
      "When you move no more than a short distance, you can move without making a sound, regardless of the surface you move across.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Take Their Measure",
    type: "Investigator",
    supernatural: false,
    tier: 4,
    description:
      "You learn the level of all creatures you can see. If they have any special weaknesses (such as a vulnerability to fire), you learn what those are. Action",
    stat: "Intellect",
    pointsRequired: 3,
    stress: 0,
  },
  {
    name: "Versatile Mind",
    type: "Investigator",
    supernatural: false,
    tier: 4,
    description:
      "When you make a Speed defense roll, you can use points from your Intellect Pool instead of your Speed Pool.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Supernatural Senses",
    type: "Investigator",
    supernatural: true,
    tier: 4,
    description:
      "You have an uncanny intuition when it comes to finding things. While exploring, you can extend your senses up to 1 mile (1.6 km) in any direction and ask the GM a very simple, general question—usually a yes-or-no question—about that area, such as “Are there any bodies buried in that yard?” If the answer you seek is not in the area, you receive no information. Action.",
    stat: "Intellect",
    pointsRequired: 4,
    stress: 3,
  },
  {
    name: "Combat Prowess",
    type: "Protector",
    supernatural: false,
    tier: 1,
    description:
      "You add 1 additional point of damage to one type of attack of your choice: melee attacks or ranged attacks. You can choose this up to two times, once for melee and once for ranged.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "No Need for Weapons",
    type: "Protector",
    supernatural: false,
    tier: 1,
    description:
      "When you make an unarmed attack (such as a punch or kick), you deal 2 additional points of damage.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "One Against Many",
    type: "Protector",
    supernatural: false,
    tier: 1,
    description:
      "Sometimes you’ve got to deal with a group of enemies, or even a swarm of enemies (rats, spiders, or worse). When this happens, perhaps the best you can do by yourself is control where everyone in the fight can or cannot go. You attempt an attack against the highest-level enemy, and if successful, in lieu of inflicting damage, you affect all the foes within an immediate distance in one of two ways: either they must move within an immediate area as you direct, or they are prevented from moving into a space in immediate range that you choose. You can use the latter option to keep them away from allies (as long as the allies don’t move), but you can’t keep them away from you in this way. The foes affected must be level 1, although you can spend additional points from your Speed Pool to affect higher levels, with each point increasing the affected creature level by 1. You must always affect the highest-level foe, so if you face a level 3 cultist and his thirty level 1 rats, you must spend 3 Speed points. Action.",
    stat: "Speed",
    pointsRequired: 1,
    stress: 0,
  },
  {
    name: "Other Knowledge",
    type: "Protector",
    supernatural: false,
    tier: 1,
    description:
      "You aren’t just a brute—you have other areas of interest as well. You are trained in one non-physical skill of your choosing in which you don’t already have training.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Overwatch",
    type: "Protector",
    supernatural: false,
    tier: 1,
    description:
      "You use a ranged weapon to target a limited area (such as a doorway, a hallway, or the eastern side of a clearing) and make an attack against the next viable target to enter that area, acting just before they act. You also negate any benefit the target would have from cover, position, range, or visibility. Further, you inflict 1 additional point of damage with the attack. You can remain on overwatch as long as you wish, within reason. Action.",
    stat: "Intellect",
    pointsRequired: 1,
    stress: 0,
  },
  {
    name: "Physical Skills",
    type: "Protector",
    supernatural: false,
    tier: 1,
    description:
      "You are trained in endurance or gymnastics. If you are already trained in one or both, this does not improve them.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Protector",
    type: "Protector",
    supernatural: false,
    tier: 1,
    description:
      "You designate a single character to be your charge. You can change this freely every round, but you can have only one charge at a time. As long as that charge is within immediate range, they gain an asset for Speed defense tasks because you have their back.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Slow Them Down",
    type: "Protector",
    supernatural: false,
    tier: 1,
    description:
      "This is a pummeling melee attack or a covering-fire ranged attack. Your attack inflicts 1 less point of damage than normal, but it dazes your target for one round, during which time their tasks are hindered and they move only half as fast as normal. Action.",
    stat: "Might/Speed",
    pointsRequired: 1,
    stress: 0,
  },
  {
    name: "Take The Hit",
    type: "Protector",
    supernatural: false,
    tier: 1,
    description:
      "If someone you are close enough to touch is struck and will suffer damage, you can take the hit instead. The other person suffers no damage, and you gain 3 points of Stress regardless of the damage that would have been originally dealt.",
    stat: "Might",
    pointsRequired: 2,
    stress: 3,
  },
  {
    name: "Bodyguard",
    type: "Protector",
    supernatural: false,
    tier: 2,
    description:
      "If you’re standing next to an ally, that ally’s initiative tasks are eased.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Coping With The Impossible",
    type: "Protector",
    supernatural: false,
    tier: 2,
    description:
      "When faced with something supernatural and difficult (or impossible) to harm by any normal means, you improvise a way to use the environment or the situation to cause the target to lose its next turn if you succeed at an Intellect-based task. Once you affect a target with this ability, further attempts to use this ability on the same target are hindered. Action.",
    stat: "Intellect",
    pointsRequired: 2,
    stress: 0,
  },
  {
    name: "Intimidating Demeanor",
    type: "Protector",
    supernatural: false,
    tier: 2,
    description:
      "You gain an asset when attempting to intimidate someone that can see you while you display a threat of violence.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Quick Recovery",
    type: "Protector",
    supernatural: false,
    tier: 2,
    description: "Your ten-minute recovery roll is only a single action.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Scarred and Hardened",
    type: "Protector",
    supernatural: false,
    tier: 2,
    description:
      "You reduce the Stress you suffer from physical injury by 1. You still suffer Stress from mental shock or despair normally.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Skill with Attacks",
    type: "Protector",
    supernatural: false,
    tier: 2,
    description:
      "Choose one type of attack in which you are not already trained: light bashing, light bladed, light ranged, medium bashing, medium bladed, medium ranged, heavy bashing, heavy bladed, or heavy ranged. You are trained in attacks using that type of weapon. You can select this ability multiple times. Each time you select it, you must choose a different type of attack.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Skill with Defence",
    type: "Protector",
    supernatural: false,
    tier: 2,
    description:
      "Choose one type of defense task in which you are not already trained: Might, Speed, or Intellect. You are trained in defense tasks of that type.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Stand Watch",
    type: "Protector",
    supernatural: false,
    tier: 2,
    description:
      "While standing watch (mostly remaining in place for an extended period of time), you unfailingly remain awake and alert for up to eight hours. During this time, you are trained in perception tasks as well as stealth tasks to conceal yourself from those who might approach. Action to initiate.",
    stat: "Might",
    pointsRequired: 2,
    stress: 0,
  },
  {
    name: "Support the Team",
    type: "Protector",
    supernatural: false,
    tier: 2,
    description:
      "While you stand watch and take no other actions, allies within a short distance gain an asset to their perception tasks, as they know you’ve got their backs. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Combat Media",
    type: "Protector",
    supernatural: false,
    tier: 3,
    description:
      "You are trained in healing. Further, if a person has moved to the dead step of the damage track and you can reach them within one round, you can use your action to keep them from dying. They remain debilitated and are most likely unconscious. They will need more formal medical attention (such as in a lengthy hospital stay) to recover. Action.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Deadly Aim",
    type: "Protector",
    supernatural: false,
    tier: 3,
    description:
      "For the next minute, all ranged attacks you make inflict 2 additional points of damage. Action to initiate.",
    stat: "Speed",
    pointsRequired: 3,
    stress: 0,
  },
  {
    name: "Lunge",
    type: "Protector",
    supernatural: false,
    tier: 3,
    description:
      "You extend yourself for a powerful stab or smash. The awkward lunge hinders the attack roll. If your attack is successful, it inflicts 4 additional points of damage. Action.",
    stat: "Might",
    pointsRequired: 2,
    stress: 0,
  },
  {
    name: "Reaction",
    type: "Protector",
    supernatural: false,
    tier: 3,
    description:
      "If a creature you attacked on your last turn with a melee attack uses its action to move out of immediate range, you gain an action to attack the creature as a parting blow, even if you have already taken a turn in the round. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Seen Some… Stuff",
    type: "Protector",
    supernatural: false,
    tier: 3,
    description:
      "You reduce the Stress you suffer from mental shock or despair by 1. You still suffer Stress from physical injury normally. Enabler.",
    stat: "Speed",
    pointsRequired: 2,
    stress: 0,
  },
  {
    name: "Spray",
    type: "Protector",
    supernatural: false,
    tier: 3,
    description:
      "If a weapon has the ability to fire rapid shots without reloading (usually called a rapid-fire weapon, such as a submachine gun), you can spray multiple shots around your target to increase the chance of hitting. This ability uses 1d6 + 1 rounds of ammo (or all the ammo in the weapon, if it has less than the number rolled). If the attack is successful, it deals 1 less point of damage than normal. You can also use this ability on multiple thrown weapons (stones, shuriken, daggers, and so on) if they are all within reach. Action.",
    stat: "Intellect",
    pointsRequired: 3,
    stress: 0,
  },
  {
    name: "Tactical Plan",
    type: "Protector",
    supernatural: false,
    tier: 3,
    description:
      "You put in the time to develop a strategy for an upcoming trip to a location you can study records and/or anecdotes about. If you visit afterward, you and up to five allies who accompany you—to whom you explain your plan—gain three of the following benefits (your choice) for that particular visit: ease their first initiative roll, ignore first point of Stress, ease first perception roll, ease first interaction roll, ease first defense roll, or ease any task to flee/escape the location. Action to initiate; one hour to devise plan.",
    stat: "Intellect",
    pointsRequired: 3,
    stress: 0,
  },
  {
    name: "Tough",
    type: "Protector",
    supernatural: false,
    tier: 3,
    description:
      "You can take punishment beyond what others can. You gain an additional step in your damage track between hale and impaired called hurt. Other than being one step closer to impaired, hurt imposes no changes to your character. Basically, you’re sore and bruised, but it’s nothing serious. Walk it off. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Vigilance",
    type: "Protector",
    supernatural: false,
    tier: 3,
    description:
      "You take a cautious approach to combat, focusing more on protecting yourself than on hurting your opponents. While this ability is active, you gain an asset on Speed defense rolls, and your attacks are hindered. This effect lasts for as long as you wish, but it ends if no combat is taking place within range of your senses. Action to initiate.",
    stat: "Intellect",
    pointsRequired: 2,
    stress: 0,
  },
  {
    name: "Impossible Strength",
    type: "Protector",
    supernatural: true,
    tier: 3,
    description:
      "For the next minute, you possess inhuman strength. You gain an asset on any noncombat action requiring physical strength, and +2 to your Might Edge. You could lift a small car. You could toss a full file cabinet across the room. In melee combat, you inflict 4 additional points of damage. Action to initiate.",
    stat: "Might",
    pointsRequired: 3,
    stress: 3,
    EdgeBonusStat: "Might",
    EdgeBonus: 2,
  },
  {
    name: "Amazing Effort",
    type: "Protector",
    supernatural: false,
    tier: 4,
    description:
      "Choose either Might Effort or Speed Effort. When you apply at least one level of that kind of Effort to a noncombat task, you get a free level of Effort on that task. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Bury the Bodies",
    type: "Protector",
    supernatural: false,
    tier: 4,
    description:
      "You gain an asset to any action involved in covering up a crime scene, a scene of violence, a break-in, or something similar. This includes speaking with the authorities. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Capable Fighter",
    type: "Protector",
    supernatural: false,
    tier: 4,
    description: "Your attacks deal 1 additional point of damage. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Expert Bodyguard",
    type: "Protector",
    supernatural: false,
    tier: 4,
    description:
      "Once per turn, choose one ally that’s next to you; their defense tasks are eased. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Free from Danger",
    type: "Protector",
    supernatural: false,
    tier: 4,
    description:
      "If you do nothing else as your action, you can grab up to two allies (conscious or otherwise, and even if they are held fast by something) and move them a short distance. For the remainder of that round, you and they have an asset on defense rolls. Action.",
    stat: "Might",
    pointsRequired: 4,
    stress: 0,
  },
  {
    name: "Arc Spray",
    type: "Protector",
    supernatural: false,
    tier: 5,
    description:
      "If a weapon has the ability to fire rapid shots without reloading (usually called a rapid-fire weapon, such as a submachine gun), you can fire your weapon at up to three adjacent targets at once. Make a separate hindered attack roll against each target. Action.",
    stat: "Speed",
    pointsRequired: 3,
    stress: 0,
  },
  {
    name: "Got Your Back",
    type: "Protector",
    supernatural: false,
    tier: 5,
    description:
      "You’re constantly giving your friends a quick helping hand. If an ally within immediate distance of you fails at a physical task, including an attack or defense roll, you can immediately allow that player to reroll. If the second roll also fails, you gain 1 point of Stress. Enabler.",
    stat: "Speed",
    pointsRequired: 4,
    stress: 0,
  },
  {
    name: "Improved Success",
    type: "Protector",
    supernatural: false,
    tier: 5,
    description:
      "When you roll a 17 or higher on an attack roll that deals damage, you deal 1 additional point of damage. For instance, if you roll a natural 18, which normally deals 2 extra points of damage, you instead deal 3 extra points. If you roll a natural 20 and choose to deal damage rather than achieve a special major effect, you deal 5 extra points of damage rather than 4. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Mastery With Attacks",
    type: "Protector",
    supernatural: false,
    tier: 5,
    description:
      "Choose one type of attack in which you are trained: light bashing, light bladed, light ranged, medium bashing, medium bladed, medium ranged, heavy bashing, heavy bladed, or heavy ranged. You are specialized in attacks using that type of weapon. Enabler. (If you aren’t trained in an attack, select Skill With Attacks to become trained in that attack.)",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Mastery With Defence",
    type: "Protector",
    supernatural: false,
    tier: 5,
    description:
      "Choose one type of defense task in which you are trained: Might, Speed, or Intellect. You are specialized in defense tasks of that type. You can select this ability up to three times. Each time you select it, you must choose a different type of defense task. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Parry",
    type: "Protector",
    supernatural: false,
    tier: 5,
    description:
      "You can deflect incoming attacks quickly. When you activate this ability, for the next ten rounds you ease all Speed defense rolls. Enabler.",
    stat: "Speed",
    pointsRequired: 5,
    stress: 0,
  },
  {
    name: "Shrug It Off",
    type: "Protector",
    supernatural: false,
    tier: 5,
    description:
      "You ignore the negative effects of your first Stress level. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Savagery",
    type: "Protector",
    supernatural: true,
    tier: 5,
    description:
      "You call upon some of the most visceral, primal fears and draw power to change into a savage, inhuman beast for an hour. In this new form, you gain +8 to your Might Pool, +2 to your Might Edge, +4 to your Speed Pool, and +2 to your Speed Edge. While in beast form, you can’t spend Intellect points for any reason other than to try to change to your normal form before the one-hour duration is over (a difficulty 2 task). In addition, you attack any and every living creature within short range. After you revert to your normal form, you take a –1 penalty to all rolls for one hour. If you did not kill and eat at least one substantial creature while in beast form, the penalty increases to –2 and affects all your rolls for the next 24 hours. Eating an intelligent creature gives you 3 points of Stress. Action to change or change back.",
    stat: "Might",
    pointsRequired: 5,
    stress: 3,
    EdgeBonusStat: "Might/Speed",
    EdgeBonus: 4 / 2,
    PoolBonusStat: "Might/Speed",
    PoolBonus: 8 / 4,
  },
  {
    name: "Again and Again",
    type: "Protector",
    supernatural: false,
    tier: 6,
    description:
      "You can take an additional action in a round in which you have already acted. Enabler.",
    stat: "Speed",
    pointsRequired: 8,
    stress: 0,
  },
  {
    name: "Beacon of Hope",
    type: "Protector",
    supernatural: false,
    tier: 6,
    description:
      "If you make a successful attack roll, you can choose one ally within a short distance that can see you. They are inspired by your success and their next task is eased. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Fight On",
    type: "Protector",
    supernatural: false,
    tier: 6,
    description:
      "You do not suffer the normal penalties for being impaired on the damage track. If debilitated, instead of suffering the normal penalty of being unable to take most actions, you can continue to act; however, all tasks are hindered. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Finishing Blow",
    type: "Protector",
    supernatural: false,
    tier: 6,
    description:
      "If your foe is prone, stunned, or somehow helpless or incapacitated when you strike, you inflict 7 additional points of damage on a successful hit. Enabler.",
    stat: "Might",
    pointsRequired: 5,
    stress: 0,
  },
  {
    name: "Spin Attack",
    type: "Protector",
    supernatural: false,
    tier: 6,
    description:
      "You stand still and make attacks against up to five foes, all as part of the same action in one round. All of the attacks have to be the same sort of attack (melee or ranged). Make a separate attack roll for each foe. You remain limited by the amount of Effort you can apply on one action. Anything that modifies your attack or damage applies to all of these attacks. In addition to the normal options for using Effort, you can use Effort to increase the number of foes you can attack with this ability (one additional foe per level of Effort used in this way). Action.",
    stat: "Speed",
    pointsRequired: 5,
    stress: 0,
  },
  {
    name: "Self-Sacrifice",
    type: "Protector",
    supernatural: true,
    tier: 6,
    description:
      "You take no action other than to stand and defend for one round. During this round, all foes within long range will choose to attack you rather than your allies, drawn to you irresistibly (no roll needed). During this round, you ignore minor injuries (Stress, other than the cost of this ability) and you ignore the first serious injury (damage track move) you suffer. Action.",
    stat: "Might",
    pointsRequired: 6,
    stress: 5,
  },
  {
    name: "Connected",
    type: "Elocutionist",
    supernatural: false,
    tier: 1,
    description:
      "You know people who get things done—not just respected people in positions of authority, but also a variety of online hackers and regular street criminals. These people are not necessarily your friends and might not be trustworthy, but they owe you a favor. You and the GM should work out the details of your contacts. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "De-Stress",
    type: "Elocutionist",
    supernatural: false,
    tier: 1,
    description:
      "While resting or relaxing with allies for an hour, you and they lose 1 more point of Stress than normal. Enabler.",
    stat: "Intellect",
    pointsRequired: 1,
    stress: 0,
  },
  {
    name: "Encouragement",
    type: "Elocutionist",
    supernatural: false,
    tier: 1,
    description:
      "While you maintain this ability through ongoing inspiring oration, your allies within short range ease one of the following task types (your choice): defense tasks, attack tasks, or tasks related to any skill that you are trained or specialized in. Action.",
    stat: "Intellect",
    pointsRequired: 1,
    stress: 0,
  },
  {
    name: "Enthrall",
    type: "Elocutionist",
    supernatural: false,
    tier: 1,
    description:
      "While talking, you grab and keep another creature’s attention, even if the creature can’t understand you. For as long as you do nothing but speak (you can’t even move), the other creature takes no actions other than to defend itself, even over multiple rounds. If the creature is attacked, the effect ends. Action.",
    stat: "Intellect",
    pointsRequired: 1,
    stress: 0,
  },
  {
    name: "Inner Defense",
    type: "Elocutionist",
    supernatural: false,
    tier: 1,
    description:
      "Life’s trials have toughened you and made you hard to read. You are trained in any task to resist another creature’s attempt to discern your true feelings, beliefs, or plans. You are likewise trained in resisting torture, telepathic intrusion, and mind control. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Knowledge Skills",
    type: "Elocutionist",
    supernatural: false,
    tier: 1,
    description:
      "You are trained in two skills in which you are not already trained. Choose two areas of knowledge such as history, geography, psychology, and so on. You can select this ability multiple times. Each time you select it, you must choose two different skills. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Secret Agendas",
    type: "Elocutionist",
    supernatural: false,
    tier: 1,
    description:
      "When speaking with at least two different NPCs for at least a minute, you pick up on subtle cues to determine one of two things (you choose): • The relationship between the NPCs (including their actual feelings about each other, at least generally). • If there are at least three NPCs, you pick the odd one out. You determine which of the group is least like the others. For example, if talking to a married couple secretly on the verge of divorce, you can pick up on subtle indications of resentment or concealed hostility. If you’re interacting with a group of people but one of them secretly works for The Web, you can pick up on something odd about them (but not specific details). Enabler.",
    stat: "Intellect",
    pointsRequired: 1,
    stress: 0,
  },
  {
    name: "Understanding",
    type: "Elocutionist",
    supernatural: false,
    tier: 1,
    description:
      "You observe or study a creature or object. Your next interaction with that creature or object gains one asset. Action.",
    stat: "Intellect",
    pointsRequired: 1,
    stress: 0,
  },
  {
    name: "Verbal Disguise",
    type: "Elocutionist",
    supernatural: false,
    tier: 1,
    description:
      "You can mimic the voice and speech patterns of a person you have heard speak before, allowing you to make one significant statement. If the person you are speaking to sees you, they will not fall for the deception, so this ability is likely best used over the telephone, in the dark, or with a heavy physical disguise. You can continue to use this ability, but the cost is 1 Intellect point for each important statement you make. This ability doesn’t make you any more persuasive—it merely disguises who is speaking. If the GM rules that you’ve said something the listener simply cannot believe the mimicked speaker would say, you immediately fail; if you’ve said more than one thing, the listener knows that none of it has come from the mimicked speaker. Enabler.",
    stat: "Intellect",
    pointsRequired: 1,
    stress: 0,
  },
  {
    name: "Agitate",
    type: "Elocutionist",
    supernatural: false,
    tier: 2,
    description:
      "You shout at a target you can see and who can easily hear you, and on a successful Intellect-based roll, they move an immediate distance in any direction you wish (because they’re startled, they heed a fake warning, or they’re otherwise unconsciously induced to do so). Action.",
    stat: "Intellect",
    pointsRequired: 2,
    stress: 0,
  },
  {
    name: "Cold Reading",
    type: "Elocutionist",
    supernatural: false,
    tier: 2,
    description:
      "When you spend at least five minutes talking to a person, you can ask the GM one question about that person and get an answer. Alternatively, you can forgo the question and simply ease all tasks involving interaction with the person for 24 hours. You cannot use this more than one time per person per 24 hours. Action to initiate; five minutes to complete.",
    stat: "Intellect",
    pointsRequired: 2,
    stress: 0,
  },
  {
    name: "Defuse",
    type: "Elocutionist",
    supernatural: false,
    tier: 2,
    description:
      "During the course of an investigation, your questions sometimes elicit an angry or even violent response. Through dissembling, verbal distraction, calming words, or similar evasion, you prevent a person from attacking anyone or anything for one round, and your next interaction with them is eased. Action.",
    stat: "Intellect",
    pointsRequired: 1,
    stress: 0,
  },
  {
    name: "Disincentivize",
    type: "Elocutionist",
    supernatural: false,
    tier: 2,
    description:
      "With some demoralizing words, you hinder all actions attempted by any number of targets within short range who can understand you. You choose which targets are affected. Affected targets’ actions are hindered for one round. Action.",
    stat: "Intellect",
    pointsRequired: 1,
    stress: 0,
  },
  {
    name: "Gather Intelligence",
    type: "Elocutionist",
    supernatural: false,
    tier: 2,
    description:
      "While within or near a large group of people, you can ask around about any topic you choose and come away with useful information. You can ask a specific question, or you can simply obtain general facts. You also get a good idea of the general layout of the location involved, note the presence of all major sites, and perhaps even notice obscure details. Action to initiate; about an hour to complete.",
    stat: "Intellect",
    pointsRequired: 2,
    stress: 0,
  },
  {
    name: "Inspire Aggression",
    type: "Elocutionist",
    supernatural: false,
    tier: 2,
    description:
      "Your words twist the mind of a character within short range who is able to understand you, unlocking their more primitive instincts. As a result, they gain an asset on their Might-based attack rolls for one minute. Action.",
    stat: "Intellect",
    pointsRequired: 2,
    stress: 0,
  },
  {
    name: "Inspiring Ease",
    type: "Elocutionist",
    supernatural: false,
    tier: 2,
    description:
      "Through stories, songs, art, or other forms of entertainment, you inspire your friends. After spending 24 hours with you, once per day each of your friends can ease one task of their choice. This benefit is ongoing while you remain in the friend’s company. It ends if you leave, but it resumes if you return to the friend’s company within 24 hours. If you leave the friend’s company for more than 24 hours, you must spend another 24 hours together to reactivate the benefit. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Quick Wits",
    type: "Elocutionist",
    supernatural: false,
    tier: 2,
    description:
      "When performing a task that would normally require spending points from your Intellect Pool, you can spend points from your Speed Pool instead. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Skill With Defense",
    type: "Elocutionist",
    supernatural: false,
    tier: 2,
    description:
      "Choose one type of defense task in which you are not already trained: Might, Speed, or Intellect. You are trained in defense tasks of that type. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Anticipate Attack",
    type: "Elocutionist",
    supernatural: false,
    tier: 3,
    description:
      "You can sense when and how creatures attacking you will make their attacks. Your Speed defense rolls are eased for one minute. Action.",
    stat: "Intellect",
    pointsRequired: 4,
    stress: 0,
  },
  {
    name: "Cover Story",
    type: "Elocutionist",
    supernatural: false,
    tier: 3,
    description:
      "After studying (either up close or from afar) a group, organization, or individual for at least five minutes, you come up with a cover story—an elaborate lie—that the group or individual in question is very likely to believe. If you or anyone else uses the cover story, any deception, persuasion, disguise, or similar task related to the cover story is eased. This benefit lasts until the cover story is irrefutably proven false (which might never happen). Action to initiate.",
    stat: "Intellect",
    pointsRequired: 4,
    stress: 0,
  },
  {
    name: "Heightened Skills",
    type: "Elocutionist",
    supernatural: false,
    tier: 3,
    description:
      "You are trained in two tasks of your choosing (other than attacks or defense). If you choose a task you’re already trained in, you instead become specialized in that task. You can’t choose a task you’re already specialized in. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Look for the Tell",
    type: "Elocutionist",
    supernatural: false,
    tier: 3,
    description:
      "After spending at least one minute with a person in conversation, you know when they are lying for the next minute. Action to initiate.",
    stat: "Intellect",
    pointsRequired: 4,
    stress: 0,
  },
  {
    name: "Scarred and Hardened",
    type: "Elocutionist",
    supernatural: false,
    tier: 3,
    description:
      "You reduce the Stress you suffer from physical injury by 1. You still suffer Stress from mental shock or despair normally. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Skill With Attacks",
    type: "Elocutionist",
    supernatural: false,
    tier: 3,
    description:
      "Choose one type of attack in which you are not already trained: light bashing, light bladed, light ranged, medium bashing, medium bladed, medium ranged, heavy bashing, heavy bladed, or heavy ranged. You are trained in attacks using that type of weapon. You can select this ability multiple times. Each time you select it, you must choose a different type of attack. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Spur Effort",
    type: "Elocutionist",
    supernatural: false,
    tier: 3,
    description:
      "Choose an ally within immediate range. If that character applies Effort to a task on their next turn, they get a free level of Effort on that task. Enabler.",
    stat: "Intellect",
    pointsRequired: 5,
    stress: 0,
  },
  {
    name: "Stress",
    type: "Elocutionist",
    supernatural: false,
    tier: 3,
    description:
      "Your terrifying, insidious words impose 3 points of Stress (4 points of damage on NPCs) on up to five people you choose that can hear and understand you within short range. Make separate attack rolls against each creature. Action.",
    stat: "Intellect",
    pointsRequired: 5,
    stress: 0,
  },
  {
    name: "Understanding Why",
    type: "Elocutionist",
    supernatural: false,
    tier: 3,
    description:
      "If you succeed at a discerning motive task, you fully understand a person’s motives and the root causes for why they do what they do. You may not get details, but you get a fair bit of general insight. You might, for example, ascertain that a murderer has a deep-seated insecurity, or that the person helping them owed them a huge debt. Action.",
    stat: "Intellect",
    pointsRequired: 4,
    stress: 0,
  },
  {
    name: "Terrorize",
    type: "Elocutionist",
    supernatural: true,
    tier: 3,
    description:
      "A creature that can understand you within a short distance suffers 3 points of Stress (4 points of damage to an NPC) and spends their next action fleeing from you as quickly as they can. They will not approach you for an hour afterward unless threatened. Action.",
    stat: "Might",
    pointsRequired: 4,
    stress: 3,
  },

  // Tier 4 (some abilities are repeats with higher tier)
  {
    name: "Anticipate Attack",
    type: "Elocutionist",
    supernatural: false,
    tier: 4,
    description:
      "You can sense when and how creatures attacking you will make their attacks. Your Speed defense rolls are eased for one minute. Action.",
    stat: "Intellect",
    pointsRequired: 4,
    stress: 0,
  },
  {
    name: "Cover Story",
    type: "Elocutionist",
    supernatural: false,
    tier: 4,
    description:
      "After studying (either up close or from afar) a group, organization, or individual for at least five minutes, you come up with a cover story—an elaborate lie—that the group or individual in question is very likely to believe. If you or anyone else uses the cover story, any deception, persuasion, disguise, or similar task related to the cover story is eased. This benefit lasts until the cover story is irrefutably proven false (which might never happen). Action to initiate.",
    stat: "Intellect",
    pointsRequired: 4,
    stress: 0,
  },
  {
    name: "Heightened Skills",
    type: "Elocutionist",
    supernatural: false,
    tier: 4,
    description:
      "You are trained in two tasks of your choosing (other than attacks or defense). If you choose a task you’re already trained in, you instead become specialized in that task. You can’t choose a task you’re already specialized in. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Look for the Tell",
    type: "Elocutionist",
    supernatural: false,
    tier: 4,
    description:
      "After spending at least one minute with a person in conversation, you know when they are lying for the next minute. Action to initiate.",
    stat: "Intellect",
    pointsRequired: 4,
    stress: 0,
  },
  {
    name: "Scarred and Hardened",
    type: "Elocutionist",
    supernatural: false,
    tier: 4,
    description:
      "You reduce the Stress you suffer from physical injury by 1. You still suffer Stress from mental shock or despair normally. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Skill With Attacks",
    type: "Elocutionist",
    supernatural: false,
    tier: 4,
    description:
      "Choose one type of attack in which you are not already trained: light bashing, light bladed, light ranged, medium bashing, medium bladed, medium ranged, heavy bashing, heavy bladed, or heavy ranged. You are trained in attacks using that type of weapon. You can select this ability multiple times. Each time you select it, you must choose a different type of attack. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Spur Effort",
    type: "Elocutionist",
    supernatural: false,
    tier: 4,
    description:
      "Choose an ally within immediate range. If that character applies Effort to a task on their next turn, they get a free level of Effort on that task. Enabler.",
    stat: "Intellect",
    pointsRequired: 5,
    stress: 0,
  },
  {
    name: "Stress",
    type: "Elocutionist",
    supernatural: false,
    tier: 4,
    description:
      "Your terrifying, insidious words impose 3 points of Stress (4 points of damage on NPCs) on up to five people you choose that can hear and understand you within short range. Make separate attack rolls against each creature. Action.",
    stat: "Intellect",
    pointsRequired: 5,
    stress: 0,
  },
  {
    name: "Understanding Why",
    type: "Elocutionist",
    supernatural: false,
    tier: 4,
    description:
      "If you succeed at a discerning motive task, you fully understand a person’s motives and the root causes for why they do what they do. You may not get details, but you get a fair bit of general insight. You might, for example, ascertain that a murderer has a deep-seated insecurity, or that the person helping them owed them a huge debt. Action.",
    stat: "Intellect",
    pointsRequired: 4,
    stress: 0,
  },
  {
    name: "Terrorize",
    type: "Elocutionist",
    supernatural: true,
    tier: 4,
    description:
      "A creature that can understand you within a short distance suffers 3 points of Stress (4 points of damage to an NPC) and spends their next action fleeing from you as quickly as they can. They will not approach you for an hour afterward unless threatened. Action.",
    stat: "Might",
    pointsRequired: 4,
    stress: 3,
  },

  // Tier 5
  {
    name: "Performance",
    type: "Elocutionist",
    supernatural: false,
    tier: 5,
    description:
      "You let your voice become your instrument. For one hour, you speak with absolute clarity and smoothness, using any manner of tones, vocal ranges, and accents. You can even perfectly imitate the voices of whomever you choose. Anyone hearing you is impressed and positively predisposed to you. For 24 hours, you gain an asset on any interaction task involving them. Action to initiate.",
    stat: "Intellect",
    pointsRequired: 4,
    stress: 0,
  },
  {
    name: "Shrug It Off",
    type: "Elocutionist",
    supernatural: false,
    tier: 5,
    description:
      "You ignore the negative effects of your first Stress level. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Soft Speech",
    type: "Elocutionist",
    supernatural: false,
    tier: 5,
    description:
      "You convince someone to confide in you in a very short amount of time. They see you not only as a friend but as a trusted confidant. After just one minute of conversation, you need make no further rolls to get the person to tell you literally anything. Enabler.",
    stat: "Intellect",
    pointsRequired: 5,
    stress: 0,
  },
  {
    name: "Stimulate",
    type: "Elocutionist",
    supernatural: false,
    tier: 5,
    description:
      "Your words encourage a creature you touch who can understand you. The next action they take is eased by three steps. Action.",
    stat: "Intellect",
    pointsRequired: 6,
    stress: 0,
  },
  {
    name: "Control",
    type: "Elocutionist",
    supernatural: true,
    tier: 5,
    description:
      "You control the actions of a creature within a short distance who can understand you. This lasts for ten minutes or until they are out of range. If you compel them to do something they would never normally do, you must roll again to maintain your effect. Action.",
    stat: "Intellect",
    pointsRequired: 5,
    stress: 3,
  },

  // Tier 6
  {
    name: "Think Your Way Out",
    type: "Elocutionist",
    supernatural: false,
    tier: 6,
    description:
      "You can use points from your Intellect Pool rather than your Might Pool or Speed Pool on any noncombat action. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Inspiring Success",
    type: "Elocutionist",
    supernatural: false,
    tier: 6,
    description:
      "When you learn this ability, choose one of the following with your group: Might tasks, Speed tasks, or Intellect tasks. When you apply a level of Effort on a task related to that stat and you succeed on your roll, choose another character within short range. On their next turn, that character has an asset on the next task they attempt using that stat. Enabler.",
    stat: "Intellect",
    pointsRequired: 6,
    stress: 0,
  },
  {
    name: "Mastery With Defense",
    type: "Elocutionist",
    supernatural: false,
    tier: 6,
    description:
      "Choose one type of defense task in which you are trained: Might, Speed, or Intellect. You are specialized in defense tasks of that type. You can select this ability up to three times. Each time you select it, you must choose a different type of defense task. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Soothing Words",
    type: "Elocutionist",
    supernatural: false,
    tier: 6,
    description:
      "A creature that you speak with for at least ten minutes loses all of their accumulated Stress. Action to initiate.",
    stat: "Intellect",
    pointsRequired: 6,
    stress: 0,
  },
  {
    name: "True Communication",
    type: "Elocutionist",
    supernatural: false,
    tier: 6,
    description:
      "You establish a bond with one person or creature so uncanny that you can make yourself understood even if you don’t share a language. Further, you can communicate on just one sensory level if that’s all you have (if they can just see you but not hear you, or hear you but not see you) without any loss of understanding. Once this bond is established, it never goes away. You can bond with only one person or creature at a time. Action.",
    stat: "Intellect",
    pointsRequired: 6,
    stress: 0,
  },
  {
    name: "Condemn",
    type: "Elocutionist",
    supernatural: true,
    tier: 6,
    description:
      "Drawing upon dark forces, you relegate one person to a future of endless despair by telling them something truly horrifying about themselves (true or not) that they henceforth believe deep in their core. They lose their next action, and all their actions afterward are hindered by two steps. Most people thus affected flee if possible. Action.",
    stat: "Intellect",
    pointsRequired: 6,
    stress: 3,
  },
  {
    name: "Already Tainted",
    type: "Occultist",
    supernatural: false,
    tier: 1,
    description:
      "You begin the game with access to abilities considered supernatural. Check with the GM to make certain that this is appropriate for the campaign. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Artefact Affinity",
    type: "Occultist",
    supernatural: false,
    tier: 1,
    description:
      "Any tasks in which you identify or use an artefact are eased. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Esoteric Skills",
    type: "Occultist",
    supernatural: false,
    tier: 1,
    description:
      "Your background has led you down many strange rabbit holes. Choose two of the following skills in which you are not already trained: biology, history, identifying, philosophy, physics, publishing, religion, or researching. You become trained in these two skills. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Intuition",
    type: "Occultist",
    supernatural: false,
    tier: 1,
    description:
      "You get a weird feeling when something is not quite right. The GM decides when this ability triggers. You spend Intellect points to gain a clue about the situation.",
    stat: "Intellect",
    pointsRequired: 2,
    stress: 0,
  },
  {
    name: "Sensitive",
    type: "Occultist",
    supernatural: false,
    tier: 1,
    description:
      "For the next ten minutes, your tasks to perceive abnormal presences or influences are eased (including those that are usually imperceptible to regular people or animals). Action to initiate.",
    stat: "Intellect",
    pointsRequired: 1,
    stress: 0,
  },
  {
    name: "Slightly Sinister Skills",
    type: "Occultist",
    supernatural: false,
    tier: 1,
    description:
      "You are trained in two skills in which you are not already trained. Choose two of the following: deception, disguise, intimidation, pickpocketing, or stealth. Can be taken multiple times; choose different skills each time. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Supernatural Comprehension",
    type: "Occultist",
    supernatural: false,
    tier: 1,
    description:
      "You identify the parameters of an unnatural effect within immediate distance, like a curse, the presence of something inhuman, or a spell. Typically requires at least a minute of study and reflection. Action to initiate.",
    stat: "Intellect",
    pointsRequired: 2,
    stress: 0,
  },
  {
    name: "Understanding",
    type: "Occultist",
    supernatural: false,
    tier: 1,
    description:
      "You observe or study a creature or object. Your next interaction with that creature or object gains one asset. Action.",
    stat: "Intellect",
    pointsRequired: 1,
    stress: 0,
  },
  {
    name: "Ventriloquism",
    type: "Occultist",
    supernatural: false,
    tier: 1,
    description:
      "For one round, you make it seem as though your voice is coming from somewhere of your choosing within immediate distance. Action.",
    stat: "Intellect",
    pointsRequired: 1,
    stress: 0,
  },
  {
    name: "Mesmerism",
    type: "Occultist",
    supernatural: true,
    tier: 1,
    description:
      "You transfix a person within immediate distance. The target loses their next action and is unaware of anything that happens during the round unless attacked or shaken out. Following round, all actions are hindered. Action.",
    stat: "Intellect",
    pointsRequired: 1,
    stress: 1,
  },
  {
    name: "Cold Reading",
    type: "Occultist",
    supernatural: false,
    tier: 2,
    description:
      "When you spend at least five minutes talking to a person, you can ask the GM one question about that person and get an answer. Alternatively, forgo the question and ease all interaction tasks for 24 hours. Cannot be used more than once per person per 24 hours. Action to initiate; five minutes to complete.",
    stat: "Intellect",
    pointsRequired: 2,
    stress: 0,
  },
  {
    name: "Hoax",
    type: "Occultist",
    supernatural: false,
    tier: 2,
    description:
      "With at least ten minutes of preparation, you can use common materials to perpetrate a brief but believable fake event lasting about one round. Action to initiate.",
    stat: "Intellect",
    pointsRequired: 2,
    stress: 0,
  },
  {
    name: "Practiced With Medium Weapons",
    type: "Occultist",
    supernatural: false,
    tier: 2,
    description:
      "You can use light and medium weapons without penalty. Heavy weapons are hindered. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Seen Some... Stuff",
    type: "Occultist",
    supernatural: false,
    tier: 2,
    description:
      "You reduce the Stress you suffer from mental shock or despair by 1. Physical injury still affects you normally. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Skill With Defense",
    type: "Occultist",
    supernatural: false,
    tier: 2,
    description:
      "Choose one type of defense task in which you are not already trained: Might, Speed, or Intellect. You are trained in that type. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Spout Nonsense",
    type: "Occultist",
    supernatural: false,
    tier: 2,
    description:
      "You fast-talk your way through occult conversations, using confusing terms that confound even knowledgeable people. Each additional Intellect point can affect another person within immediate distance. Action.",
    stat: "Intellect",
    pointsRequired: 2,
    stress: 0,
  },
  {
    name: "Premonition",
    type: "Occultist",
    supernatural: true,
    tier: 2,
    description:
      "You learn one random fact about a creature, object, or location pertinent to a topic you designate. Alternatively, learn a creature’s level but nothing else about it. Action.",
    stat: "Intellect",
    pointsRequired: 2,
    stress: 0,
  },
  {
    name: "Send Thoughts",
    type: "Occultist",
    supernatural: true,
    tier: 2,
    description:
      "Mentally transmit a message to someone you know well (up to ten words or one image). Range is 1 mile plus 1 mile per additional Intellect point spent. Action.",
    stat: "Intellect",
    pointsRequired: 2,
    stress: 2,
  },
  {
    name: "Cooperative Sorcery",
    type: "Occultist",
    supernatural: true,
    tier: 3,
    description:
      "Boosts another person's supernatural ability by extending range, doubling targets, or easing the task. If the ability causes Stress, you suffer the same. Action.",
    stat: "Intellect",
    pointsRequired: 4,
    stress: 0,
  },
  {
    name: "Embracing the Unknown",
    type: "Occultist",
    supernatural: false,
    tier: 3,
    description:
      "Interaction tasks with supernatural beings are eased. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Intense Practitioner",
    type: "Occultist",
    supernatural: false,
    tier: 3,
    description:
      "If you apply at least one level of Effort to a task involving the supernatural, you get a free level of Effort. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Peering Beyond the Veil",
    type: "Occultist",
    supernatural: true,
    tier: 3,
    description:
      "Become aware of supernatural activity otherwise imperceptible: see invisible objects, hear inaudible sounds within short distance for one hour, and sense supernatural events in area from last 24 hours. Action.",
    stat: "Intellect",
    pointsRequired: 3,
    stress: 3,
  },
  {
    name: "Resistance to the Uncanny",
    type: "Occultist",
    supernatural: false,
    tier: 3,
    description:
      "Ill effects of using artefacts are mitigated; gain 1 less point of Stress than normal. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Shatter",
    type: "Occultist",
    supernatural: true,
    tier: 3,
    description:
      "Mystically detonate a small object within long range. Explodes in immediate radius, dealing 1 point of damage to all creatures and objects. Effort increases damage. Action.",
    stat: "Intellect",
    pointsRequired: 2,
    stress: 3,
  },
  {
    name: "Supernatural Resistance",
    type: "Occultist",
    supernatural: false,
    tier: 3,
    description:
      "Your defense tasks against supernatural effects are eased. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Combating the Uncanny",
    type: "Occultist",
    supernatural: false,
    tier: 4,
    description: "All attacks against supernatural beings are eased. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Heightened Skills",
    type: "Occultist",
    supernatural: false,
    tier: 4,
    description:
      "You are trained in two tasks of your choosing (other than attacks or defense). If you choose a task you’re already trained in, you instead become specialized. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Shrug It Off",
    type: "Occultist",
    supernatural: false,
    tier: 4,
    description:
      "You ignore the negative effects of your first Stress level. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Think Your Way Out",
    type: "Occultist",
    supernatural: false,
    tier: 4,
    description:
      "You can use points from your Intellect Pool rather than Might or Speed on any noncombat action. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Cypher Manifestation",
    type: "Occultist",
    supernatural: true,
    tier: 4,
    description:
      "Transform one cypher you have into a small physical object for another person to use. Counts against their cypher limit. Action.",
    stat: "Might",
    pointsRequired: 4,
    stress: 3,
  },
  {
    name: "Edit Memories",
    type: "Occultist",
    supernatural: true,
    tier: 4,
    description:
      "Reach into the mind of a person within immediate range and edit the last five minutes of memory. Action.",
    stat: "Intellect",
    pointsRequired: 4,
    stress: 3,
  },
  {
    name: "See the Truth",
    type: "Occultist",
    supernatural: false,
    tier: 5,
    description:
      "See through magical disguises, veils, illusions, and obfuscations without a roll. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Skill With Attacks",
    type: "Occultist",
    supernatural: false,
    tier: 5,
    description:
      "Choose one type of attack you’re not already trained in. You are trained in that type. Can be selected multiple times; choose different type each time. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Stern Stuff",
    type: "Occultist",
    supernatural: false,
    tier: 5,
    description:
      "You no longer suffer Stress from seeing something supernatural. All other stressful events still affect you. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Stressed Mind",
    type: "Occultist",
    supernatural: true,
    tier: 5,
    description:
      "With a touch and a whisper, a creature suffers 6 points of Stress (6 damage for an NPC). Action.",
    stat: "Intellect",
    pointsRequired: 4,
    stress: 3,
  },
  {
    name: "Vanish From Sight",
    type: "Occultist",
    supernatural: true,
    tier: 5,
    description:
      "Turn invisible for up to one minute. Can only move or manipulate objects. Talking or attacking reveals you. Action to initiate.",
    stat: "Intellect",
    pointsRequired: 5,
    stress: 4,
  },
  {
    name: "Craft Artefact",
    type: "Occultist",
    supernatural: true,
    tier: 6,
    description:
      "Create a single artefact. Process is long, difficult, and confounding. Each artefact involves months/years of work, money cost, and Stress (3 points per day, permanent loss of 3 points from stat Pools). Finished artefact equals a Tier 6 effect. GM collaborates on specifics.",
    stat: "",
    pointsRequired: 3,
    stress: 3,
  },
  {
    name: "Defending Others",
    type: "Occultist",
    supernatural: false,
    tier: 6,
    description:
      "Allies within immediate distance ease defenses against supernatural effects. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Mastery With Defense",
    type: "Occultist",
    supernatural: false,
    tier: 6,
    description:
      "Choose one type of defense task in which you are trained: Might, Speed, or Intellect. You are specialized in that type. Can select up to three times; choose different types each time. Enabler.",
    stat: "",
    pointsRequired: 0,
    stress: 0,
  },
  {
    name: "Meditative Restoration",
    type: "Occultist",
    supernatural: false,
    tier: 6,
    description:
      "Rid yourself of 3 points of Stress each minute you do nothing else. Action to initiate.",
    stat: "Intellect",
    pointsRequired: 8,
    stress: 0,
  },
  {
    name: "Ghost",
    type: "Occultist",
    supernatural: true,
    tier: 6,
    description:
      "Gain an asset to sneaking tasks for 10 minutes. Move through solid barriers at 1 foot per round, perceive while phased. Action to initiate.",
    stat: "Intellect",
    pointsRequired: 6,
    stress: 5,
  },
  {
    name: "Psychokinetic Attack",
    type: "Occultist",
    supernatural: true,
    tier: 6,
    description:
      "Pick up and hurl a heavy object at a target within short range (Intellect action, 6 damage) or unleash a shattering burst on an inanimate object no larger than half your size (Intellect roll, eased by 3 steps). Action.",
    stat: "Might",
    pointsRequired: 6,
    stress: 5,
  },
];
