const SKILLS_DATA = [
  "Astronomy",
  "Biology",
  "Carpentry",
  "Cooking",
  "Deception",
  "Defense",
  "Discerning motive",
  "Disguise",
  "Driving",
  "Electrical repair",
  "Electronics",
  "Endurance",
  "Engineering",
  "Equipment operation",
  "Forensics",
  "Geography",
  "Geology",
  "Gunsmithing",
  "Gymnastics",
  "Healing",
  "History",
  "Identifying",
  "Initiative",
  "Intimidation",
  "Leatherworking",
  "Lockpicking",
  "Mathematics",
  "Mechanics",
  "Medicine",
  "Metalworking",
  "Occultism",
  "Perception",
  "Performance",
  "Persuasion",
  "Philosophy",
  "Physics",
  "Pickpocketing",
  "Piloting",
  "Plumbing",
  "Programming",
  "Psychology",
  "Publishing",
  "Religion",
  "Researching",
  "Riding",
  "Sewing",
  "Stealth",
  "Tracking",
];

// Export for use in main HTML
if (typeof module !== "undefined" && module.exports) {
  module.exports = SKILLS_DATA;
}
